[mypy]
strict = True
python_version = 3.10
plugins = pydantic.mypy
warn_return_any = True
warn_unused_configs = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-reportlab.*]
ignore_missing_imports = True
